var tricks = [

    // Fundamentals

    //Thumbaround variationen
    {
        TrickName: "Thumbaround > Thumbaround reverse",
        anfPos: 12,
        endPos: 23,
        PalmDown: true,
        PalmNormal: true,
        PenPalm: false,
        PenBack: true,
        clockwise: false,
    },

    {
        TrickName: "Thumbaround > Thumbaround reverse",
        anfPos: 12,
        endPos: 12,
        PalmDown: true,
        PalmNormal: true,
        PenPalm: false,
        PenBack: true,
        clockwise: false,
    },

    {
        TrickName: "Thumbaround > Thumbaround reverse",
        anfPos: 23,
        endPos: 23,
        PalmDown: true,
        PalmNormal: true,
        PenPalm: false,
        PenBack: true,
        clockwise: false,
    },

    {
        TrickName: "Thumbaround > Thumbaround reverse",
        anfPos: 23,
        endPos: 12,
        PalmDown: true,
        PalmNormal: true,
        PenPalm: false,
        PenBack: true,
        clockwise: false,
    },
    
    {
        TrickName: "Sonic rev",
        anfPos: 12,
        endPos: 23,
        PalmDown: true,
        PalmNormal: true,
        PenPalm: true,
        PenBack: true,
        clockwise: false,
    },
    {
        TrickName: "Sonic",
        anfPos: 23,
        endPos: 12,
        PalmDown: true,
        PalmNormal: true,
        PenPalm: true,
        PenBack: true,
        clockwise: true,
    },
    {
        TrickName: "Sonic",
        anfPos: 34,
        endPos: 23,
        PalmDown: true,
        PalmNormal: true,
        PenPalm: true,
        PenBack: true,
        clockwise: true,
    },
    {
        TrickName: "Sonic rev",
        anfPos: 23,
        endPos: 34,
        PalmDown: true,
        PalmNormal: true,
        PenPalm: true,
        PenBack: true,
        clockwise: false,
    },
    {
        TrickName: "Twisted Sonic rev",
        anfPos: 12,
        endPos: 23,
        PalmDown: true,
        PalmNormal: true,
        PenPalm: true,
        PenBack: true,
        clockwise: false,
    },
    {
        TrickName: "Twisted Sonic ",
        anfPos: 34,
        endPos: 23,
        PalmDown: true,
        PalmNormal: true,
        PenPalm: true,
        PenBack: true,
        clockwise: true,
    },
    {
        TrickName: "Twisted Sonic",
        anfPos: 23,
        endPos: 12,
        PalmDown: true,
        PalmNormal: true,
        PenPalm: true,
        PenBack: true,
        clockwise: true,
    },
    {
        TrickName: "Twisted Sonic rev",
        anfPos: 23,
        endPos: 34,
        PalmDown: true,
        PalmNormal: true,
        PenPalm: true,
        PenBack: true,
        clockwise: false,
    },
    {
        TrickName: "Pass",
        anfPos: 12,
        endPos: 23,
        PalmDown: true,
        PalmNormal: true,
        PenPalm: true,
        PenBack: true,
        clockwise: true,
    },
    {
        TrickName: "Pass ",
        anfPos: 34,
        endPos: 23,
        PalmDown: true,
        PalmNormal: true,
        PenPalm: true,
        PenBack: true,
        clockwise: true,
    },
    {
        TrickName: "Pass ",
        anfPos: 23,
        endPos: 34,
        PalmDown: true,
        PalmNormal: true,
        PenPalm: true,
        PenBack: true,
        clockwise: true,
    },
    {
        TrickName: "Pass ",
        anfPos: 23,
        endPos: 12,
        PalmDown: true,
        PalmNormal: true,
        PenPalm: true,
        PenBack: true,
        clockwise: true,
    },
    {
        TrickName: "Demons Sonic",
        anfPos: 34,
        endPos: 12,
        PalmDown: true,
        PalmNormal: true,
        PenPalm: true,
        PenBack: true,
        clockwise: true,
    },
    {
        TrickName: "Angels Sonic",
        anfPos: 12,
        endPos: 34,
        PalmDown: true,
        PalmNormal: true,
        PenPalm: true,
        PenBack: true,
        clockwise: false,
    },

    // ++++++++++++++++++++++++++Palm Changes+++++++++++++++++++++++

    //PD -> PN

    {
        TrickName: "(Palm Normal) Neosoinc rev ",
        anfPos: 12,
        endPos: 23,
        PalmDown: true,
        PalmNormal: false,
        PenPalm: true,
        PenBack: false,
        clockwise: false,
    },
    {
        TrickName: "(Palm Normal) Pass rev ",
        anfPos: 12,
        endPos: 23,
        PalmDown: true,
        PalmNormal: false,
        PenPalm: false,
        PenBack: true,
        clockwise: false,
    },
    {
        TrickName: "(Palm Normal) Pass rev",
        anfPos: 23,
        endPos: 34,
        PalmDown: true,
        PalmNormal: false,
        PenPalm: false,
        PenBack: true,
        clockwise: false,
    },

    //PN -> PD
    {
        TrickName: "(Palm Down) Pass",
        anfPos: 34,
        endPos: 23,
        PalmDown: false,
        PalmNormal: true,
        PenPalm: true,
        PenBack: true,
        clockwise: true,
    },

    {
        TrickName: "(Palm Down) Pass",
        anfPos: 23,
        endPos: 12,
        PalmDown: false,
        PalmNormal: true,
        PenPalm: true,
        PenBack: true,
        clockwise: true,
    },

    {
        TrickName: "(Palm Down) Charge rev 12 > Pass rev",
        anfPos: 12,
        endPos: 23,
        PalmDown: false,
        PalmNormal: true,
        PenPalm: true,
        PenBack: true,
        clockwise: true,
    },

    {
        TrickName: "(Palm Down) Charge rev 23 > Pass rev",
        anfPos: 23,
        endPos: 34,
        PalmDown: false,
        PalmNormal: true,
        PenPalm: true,
        PenBack: true,
        clockwise: true,
    },

];