var penmods = '{"mods":[' +
'{ "name":"KAGAMI DC","link":"https://penmodding.pm/archives/5843","pic":"../img/kagami_dc.jpg","text":"Featured picture : credit goes to Mina. – Name : Kagami DC – Creator : Kagami – Length : 21cm – Weight : 14 g – Insert : No – Difficulty : Medium", "type":"dc"},'+
'{ "name":"AKAI DC","link":"https://penmodding.pm/archives/5613","pic":"../img/akai_dc.jpg","text":"Featured picture : credit goes to Mina. – Name : Akai DC – Creator : Akai – Length : 22.5 cm – Weight : 13 g – Insert : No – Difficulty : Easy", "type":"dc"},'+
'{ "name":"IM* Hybrid","link":"https://penmodding.pm/archives/5531","pic":"../img/im hybrid.png","text":"Featured picture : credit goes to Vôre-Tèx – Name : Ivan-Menowa* Hybrid (IM* Hybrid) – Creator : Vôre-Tèx – Length : 22cm – Weight : 22g – Insert : No – Weblink : >Vôre-Tèx blog< – Difficulty :  Medium", "type":"dc"},'+
'{ "name":"Menowa* Prize Mod","link":"https://penmodding.pm/archives/5574","pic":"../img/menowa prize mod.jpg","text":"Featured picture : credit goes to Mina. – Name : Menowa* Prize Mod – Creator : LostAngelus – Length : 21 cm – Weight : 18.4 g – Insert : No – Difficulty : Easy ", "type":"dc"},'+
'{ "name":"Nebrask Mod","link":"https://penmodding.pm/archives/5548","pic":"../img/nebrask mod.jpg","text":"Featured picture : credit goes to Ponkotu – Name : Nebrask Mod | note : in Japanese, they call it the Neobaku (neoback?) mod – Creator : Nebrask – Length : 19.5cm – Weight : 16-17g – Insert : No – Weblink : >Ponkotu blog< >Original yt tutorial< – Difficulty :  Easy-Medium", "type":"dc"},'+
'{ "name":"Bonkura Com.ssa (Comssa)","link":"https://penmodding.pm/archives/5544","pic":"../img/bonkura com.ssa.jpg","text":"Featured picture : credit goes to Vôre-Tèx – Name : Bonkura Com.ssa – Creator : Bonkura – Length : 19.5cm – Weight : 9-10g – Insert : No – Weblink : >Penspinning.fr< – Difficulty :  Super Easy ", "type":"dc"},'+
'{ "name":"Sonoda Emboss","link":"https://penmodding.pm/archives/5537","pic":"../img/sonoda emboss.jpg","text":"Featured picture : credit goes to Sonoda – Name : Sonoda Emboss mod – Creator : Sonoda – Length : 23cm – Weight : ~20g(?) – Insert : Yes – Weblink : >Sonoda Blog< – Difficulty :  Medium", "type":"dc"},'+
'{ "name":"ITEZA KT","link":"https://penmodding.pm/archives/5511","pic":"../img/iteza kt.jpg","text":"Featured picture : credit goes to Vôre-Tèx – Name : Iteza KT – Creator : Iteza – Length : 19-20cm – Weight : 14g – Insert : No – Weblink : / – Difficulty :  Super Easy", "type":"dc"},'+
'{ "name":"MOTSUUN","link":"https://penmodding.pm/archives/5461","pic":"../img/motsuun.jpg","text":"Featured picture : credit goes to Meves (Mizu) – Name : Motsuun – Creator : Meves (Mizu) – Length : 19cm – Weight : Light-medium – Insert : No – Weblink : >Meves Blog< – Difficulty :  Easy", "type":"dc"},'+
'{ "name":"DR.BT","link":"https://penmodding.pm/archives/5494","pic":"../img/dr.bt.jpg","text":"Featured picture : credit goes to Vôre-Tèx – Name : Dr.BT note : BT is for BinchoTan (stands for charcoal) >wiki explanation< – Creator : Menowa* – Length : 20.5cm – Weight : 19g(?) – Insert : No – Weblink : >Ponkotu blog< – Difficulty :  Super Easy", "type":"dc"},'+
'{ "name":"Everchix Emboss Mod","link":"https://penmodding.pm/archives/5452","pic":"../img/everchix emboss mod.jpg","text":"Featured picture : credit goes to Everchix – Name : Everchix Emboss Mod (also called EEM) – Creator : Everchix – Length : 22cm(?) – Weight : ~20g(?) – Insert : No – Weblink : / – Difficulty :  Easy~Medium", "type":"dc"},'+
'{ "name":"Menowa* KT","link":"https://penmodding.pm/archives/5448","pic":"../img/menowakt.png","text":"Featured picture : credit goes to Vôre-Tèx – Name : Menowa* KT (also called “fake KT”) – Creator : Menowa* – Length : 20cm – Weight : ~18g – Insert : No – Weblink : >Menowa* Tumblr < – Difficulty :  Easy", "type":"dc"},'+
'{ "name":"Menowa* VGG","link":"https://penmodding.pm/archives/5445","pic":"../img/menowa vgg.jpg","text":"Featured picture : credit goes to Vôre-Tèx – Name : Menowa* VGG (also called “fake vicgotgame”) – Creator : Menowa* – Length : 22cm – Weight : ~19g – Insert : No – Weblink : >Ponkotu blog< – Difficulty :  Easy", "type":"dc"},'+
'{ "name":"Energel St V2","link":"https://penmodding.pm/archives/5436","pic":"../img/energel st v2.png","text":"Featured picture : credit goes to i.suk – Name : Energel ST V2 – Creator : i.suk – Length : 23.7cm – Weight : ~18g – Insert : No – Weblink : >i.suk YT < – Difficulty :  Easy", "type":"dc"},'+
'{ "name":"Laluteskal Ballsign","link":"https://penmodding.pm/archives/5428","pic":"../img/laluteskal ballsign.jpg","text":"Featured picture : credit goes to Ponkotu – Name : Laluteskal Ballsign – Creator : Laluteskal – Length : 20.5cm – Weight : 17g – Insert : Yes – Weblink : >Ponkotu blog< – Difficulty :  Easy", "type":"dc"},'+
'{ "name":"Miyana Marvy Marker Mod","link":"https://penmodding.pm/archives/5414","pic":"../img/miyana marvy marker mod.jpg","text":"Featured picture : credit goes to Miyana – Name : Miyana Marvy Marker Mod – Creator : Miyana – Length : 20cm – Weight : ~13g – Insert : No – Weblink : >Miyana blog< note : take a look at this link to see all of Miyana’s MMM – Difficulty :  Easy", "type":"dc"},'+
'{ "name":"Vore-Tex Kt","link":"https://penmodding.pm/archives/5403","pic":"../img/vore-tex kt.jpg","text":"Featured picture : credit goes to Vôre-Tèx – Name : Vôre-Tèx KT (VT KT) – Creator : Vôre-Tèx – Length : 20cm – Weight : 15-16g – Insert : No – Weblink : >VT blog< – Difficulty :  Medium", "type":"dc"},'+
'{ "name":"Anpen Mod","link":"https://penmodding.pm/archives/5397","pic":"../img/anpen mod.jpg","text":"Featured picture : credit goes to Menowa* – Name : Anpen mod – Creator : Menowa* – Length : ~22cm – Weight : Heavy (~22g) – Insert : No – Weblink : >Menowa* blog< – Difficulty :  Easy", "type":"dc"},'+
'{ "name":"Joshin Ballsign","link":"https://penmodding.pm/archives/5343","pic":"../img/joshin ballsign.jpg","text":"Featured picture : credit goes to Joshin – Name : Joshin Ballsign – Creator : Joshin – Length : ~20 cm – Weight : ~14g – Insert : Yes – Weblink : >Joshin blog< – Difficulty : Easy", "type":"dc"},'+
'{ "name":"Menowa* Mod","link":"https://penmodding.pm/archives/5338","pic":"../img/menowa mod.png","text":"Featured picture : credit goes to Vôre-Tèx – Name : Menowa* mod – Creator : Menowa* – Length : 20 cm – Weight : 20g – Insert : No – Weblink : >Menowa* Tumblr< – Difficulty : Medium", "type":"dc"},'+
'{ "name":"KZZN Emboss","link":"https://penmodding.pm/archives/5324","pic":"../img/kzzn emboss.jpg","text":"Featured picture : credit goes to KZZN – Name : KZZN Emboss mod – Creator : KZZN – Length : ~22 cm – Weight : >25g – Insert : No – Weblink : >Kzzn Blog< – Difficulty : Easy", "type":"dc"},'+
'{ "name":"VGG Emboss Mod Replica","link":"https://penmodding.pm/archives/5280","pic":"../img/vgg emboss.jpg","text":"Featured picture : credit goes to Cloud. – Name : VGG emboss mod replica – Creator : Cloud – Length : 24 cm – Weight : ~25 g – Insert : No – Weblink : UPSB (archive), FPSB, VNPSC, PserHome – Difficulty : Medium", "type":"dc"},'+
'{ "name":"Huwng Kt","link":"https://penmodding.pm/archives/5252","pic":"../img/Huwng kt.png","text":"Featured picture : credit goes to Huwng for the picture. -Name : Huwng KT -Creator : Huwng -Length : 22.5 cm -Weight : 14 g -Outsert : No -Weblink : Huwng YouTube Tutorial -Difficulty : Easy ", "type":"dc"},'+
'{ "name":"Menowa* Emboss Mod","link":"https://penmodding.pm/archives/5017","pic":"../img/menowa emboss.png","text":"Credit goes to Vôre-Tèx for the featured picture. – Name :Menowa Emboss Mod – Ikusafude – Creator : Menowa* – Length : ~20.5cm – Weight : ~21g – Outsert : No – Weblink : Menowa’s Tumblr, Vôre-Tèx’s YouTube Video – Difficulty : Long and hard", "type":"dc"},'+
'{ "name":"I.Suk Emboss V3","link":"https://penmodding.pm/archives/4767","pic":"../img/I.Suk emboss v3.jpg","text":"Name : I.suk Emboss V3 – Creator : I.suk – Length : 24.9cm – Weight : 20g – Outsert : No – Weblink : No link – Difficulty : Easy", "type":"dc"},'+
'{ "name":"PPM Mod","link":"https://penmodding.pm/archives/4761","pic":"../img/ppm.jpg","text":"Featured picture : credit goes to Jing – Name : PPM mod – Creator : PPM – Length : 23.2 cm – Weight : 22 g – Insert : No – Weblink : Youtube – Difficulty : Easy", "type":"dc"},'+
'{ "name":"Irvine Kt","link":"https://penmodding.pm/archives/4705","pic":"../img/irvine kt.png","text":"Featured picture : credit goes to Vôre-Tèx for the picture and Mjerry56 for the making.  – Name : Irvine KT – Creator : Irvine – Length : 21 cm – Weight : 20 g – Outsert : No – Weblink : Irvine’s blog – Difficulty : Easy", "type":"dc"},'+
'{ "name":"Shadix Kt","link":"https://penmodding.pm/archives/4046","pic":"../img/shadix kt.jpg","text":"Name : Shadix KT – Creator : Shadix – Length : 20cm – Weight : ~17g – Insert : Yes – Weblink : Pen Meeting place (Japanese) – Difficulty : Easy", "type":"dc"},'+
'{ "name":"Menowa* Reimei","link":"https://penmodding.pm/archives/4011","pic":"../img/menowareimei.png","text":"Name : Reimei Mod (黎明Mod) – Creator : Menowa – Length : 20cm – Weight : 18g – Insert : Yes – Weblink : Menowa*’s blog, Vôre-Tèx’s blog – Difficulty : Easy but takes time", "type":"dc"},'+
'{ "name":"Talonplay","link":"https://penmodding.pm/archives/4004","pic":"../img/talonplay.jpg","text":"Name : TalonPlay – Creator : Bonzin – Length : 21cm (?) – Weight : Medium – Outsert : No – Weblink : Saifon’s blog – Difficulty :  Medium", "type":"dc"},'+
'{ "name":"Night Dc Mod","link":"https://penmodding.pm/archives/3148","pic":"../img/nightz dc mod.jpg","text":"Name : Nightz DC Mod – Creator : Nightz – Length : 20 cm – Weight : ~17 g – Outsert : No – Link : UPSB – Making : Middle", "type":"dc"},'+
'{ "name":"G-Mod V2","link":"https://penmodding.pm/archives/3190","pic":"../img/g-mod v2.png","text":"Name : G-Mod V2 – Creator :. Gibki – Length : 20cm – Weight :  Medium / Heavy – Insert / Outsert : No – Weblink :. G-Mod V2 (UPSB) – Making : Easy", "type":"dc"},'+
'{ "name":"J-Vic DC","link":"https://penmodding.pm/archives/3183","pic":"../img/J-Vic dc.jpg","text":"Name : J-Vic DC – Creator : Whizz – Length :  20cm – Weight : about 16g – Outsert : No, but you can add it under the gripcut – Link : UPSB – Making : Middle", "type":"dc"},'+
'{ "name":"Nautilus Mod","link":"https://penmodding.pm/archives/3131","pic":"../img/nautilus mod.jpg","text":"Name : Nautilus Mod – Creator : BurningFinger – Length : 20,5 cm w/o tips and 22 w/. – Weight : 16 g – Outsert : No – Weblink : UPSB(webarchive), PSH – Modding : Long and very complicated.", "type":"dc"},'+
'{ "name":"Pom-Pom Mod (Ivabra Pen Mod V2)","link":"https://penmodding.pm/archives/3065","pic":"../img/pom pom mod.jpg","text":"Name : Pom-pom Mod – Creator : Taeko – Length : 21cm – Weight : 20g –  Outsert : No – Weblink : FPSB – Difficulty : Hard", "type":"dc"},'+
'{ "name":"Inverse Comssa","link":"https://penmodding.pm/archives/3107","pic":"../img/inverse comssa.png","text":"Name : Inverse Comssa – Creator : ? – Length : 18cm – Weight : 12g – Outsert : Why not – Link : UPSB – Difficulty : A little bit hard", "type":"dc"},'+
'{ "name":"BSNC (BallsignNorisClub)","link":"https://penmodding.pm/archives/2019","pic":"../img/bsnc.jpg","text":"Name : BSNC ( BallsignNorisClub) – Creator : Kr4zy – Length : 21,4 cm – Weight : 13 g – Insert : Yes – Link : / – Difficulty :. Easy", "type":"dc"},'+
'{ "name":"Ivan Mod (Buster CYL V2)","link":"https://penmodding.pm/archives/3017","pic":"../img/ivan mod.jpg","text":"Name :  Ivan Mod ( Buster Cyl V2) – Creator :  Ivan – Length : 22cm – Weight : 20 g – Outsert : No – Link : Tutoriel Ivan Mod (FPSB) – Making : Medium", "type":"dc"},'+
'{ "name":"Ivabra Pen Mod","link":"https://penmodding.pm/archives/2963","pic":"../img/ivabra mod.jpg","text":"Name : Ivabra Pen Mod – Creator : Ivabra – Length : 20,5 cm – Weight : ~20 g – Outsert : No – Making : easy", "type":"dc"},'+
'{ "name":"Killergel Clear","link":"https://penmodding.pm/archives/2966","pic":"../img/KILLERGELCLEARRAINBOW.png","text":"Name : Clear KillerGel – Creator : Taeko – Length : 19,5 cm – Weight : 16 g – Insert  : Yes – Weblink : / – Difficulty : Hard", "type":"dc"},'+
'{ "name":"Joeys Dc Mod","link":"https://penmodding.pm/archives/2765","pic":"../img/joey dc mod.jpg","text":"Name : Joey’s DC Mod – Creator : Joey – Length : 19,2 cm – Weight : medium – Outsert : No – Link :  Joey’s DC Mod (Youtube) – Modding : Easy.", "type":"dc"},'+
'{ "name":"Yelo Mod","link":"https://penmodding.pm/archives/2719","pic":"../img/yelo mod.png","text":"Name : Yelo Mod – Creator : Tek – Length : 21 cm – Weight : ~16 g –  Outsert : No – Weblink : Yelo Mod (UPSB v4) – Difficulty : Easy", "type":"dc"},'+
'{ "name":"Colors Mod","link":"https://penmodding.pm/archives/5832","pic":"../img/colors_mod.jpg","text":"Featured picture : credit goes to Eban. – Name : Eban Memory DC – Creator : Unknown, this mod was gifted to Eban by another spinner – Length : 21 cm – Weight : 12 g – Insert : No – Weblink : / – Difficulty : Easy", "type":"dc"},'+
'{ "name":"Everchix Comssa","link":"https://penmodding.pm/archives/5877","pic":"../img/everchix_comssa.jpg","text":"Featured picture : credit goes to Mina. – Name : Everchix Comssa – Creator : Everchix – Length : 20.5 cm – Weight : 19 g – Insert : No – Difficulty : Medium", "type":"dc"},'+
'{ "name":"Orbia Fitline","link":"https://penmodding.pm/archives/5880","pic":"../img/Orbia_fitline.jpg","text":"Featured picture : credit goes to Mina. – Name : Oribia Fitline – Creator : Oribia – Length : 21.5 cm – Weight : 21 g – Insert : No – Difficulty : Medium", "type":"dc"},'+
'{ "name":"Kacogreen Grip Aviaire (KG GA)","link":"https://penmodding.pm/archives/5855","pic":"../img/kacogreen_grip_aviaire.jpg","text":"Featured picture : credit goes to Mina. – Name : KakoGreen Grip Aviaire (KG GA) – Creator : Megas – Length : 22 cm – Weight : 18 g – Insert : No – Difficulty : Easy", "type":"dc"},'+
'{ "name":"Vore-Tex Emboss","link":"https://penmodding.pm/archives/5800","pic":"../img/vore-tex_emboss.png","text":"Featured picture : credit goes to Vôre-Tèx – Name : Vôre-Tèx Emboss – Creator : Vôre-Tèx – Length : 20.5cm – Weight : ~16g – Insert : No – Weblink : >Vôre-Tèx blog< – Difficulty :  Medium ", "type":"dc"},'+
'{ "name":"P4P3RON Mod","link":"https://penmodding.pm/archives/5763","pic":"../img/p4p3ron_mod.jpg","text":"Featured picture : credit goes to Aceron – Name : P4P3RON mod – Creator : Aceron – Length : 20cm – Weight : 11g – Outsert : Yes – Weblink : FPSB V4 – Difficulty :  Easy", "type":"dc"},'+
'{ "name":"MENOWA* BT VGG","link":"https://penmodding.pm/archives/5677","pic":"../img/Menowa_BT_VGG.jpg","text":"Featured picture : credit goes to Menowa* – Name : Menowa* BT VGG | note : Menowa* calls it the fake VGG charcoal – Creator : Menowa* – Length : 22cm – Weight : Heavy (22g?) – Insert : No – Weblink : Ponkotu blog – Difficulty :  Easy", "type":"dc"},'+
'{ "name":"Namemory","link":"https://penmodding.pm/archives/2700","pic":"../img/namemory.jpg","text":"Name :. Namemory DC – Creator :. iColor – Length : ~20 cm – Weight : Medium –  Outsert : If you want. – Link : Namemory DC (UPSB) – Difficulty : Easy", "type":"dc"},'+
'{ "name":"Majora CYL","link":"https://penmodding.pm/archives/2654","pic":"../img/majora.jpg","text":" Name : Majora Cyl – Creator : Majora – Length : 23 cm – Weight : 22 g – Outsert : No – Link : Majora CYL (GPC) – Difficulty : Easy ", "type":"dc"},'+
'{ "name":"Stek Body","link":"https://penmodding.pm/archives/1110","pic":"../img/stek.png","text":"Ceci est une technique de Tek. Ce n’est pas réelement un mod mais plutôt une technique de moddage permettant de “colorer” un peu plus le mod. Cette technique peut être appliquable à : – Com.Ssa – Bellcolor Mod – BusterCYL – Tout les autres mods qui ont pour corps un", "type":"dc"},'+
'{ "name":"CYL 83 Mod","link":"https://penmodding.pm/archives/1108","pic":"../img/cyl 83.jpg","text":"Featured picure : credit goes to olllDumPlllo.   – Name : Cyl 83 Mod ( Tek’s Super Tip Mod ) – Creator : olllDumPlllo – Length : 21 cm – Weight : Medium – Outsert : No – Link : Cyl 83 Mod ( ThaiSpinner ) – Difficulty : Easy", "type":"dc"},'+
'{ "name":"Pirat KS aka Stuhl mod","link":"https://penmodding.pm/archives/2584","pic":"../img/stuhl.jpg","text":"Name : Pirat KS – Creator : Stuhl – Length : Long – Weight : Middle –  Outsert : No – Link : / – Difficulty :  Easy-Medium", "type":"dc"},'+
'{ "name":"Hyper Sign","link":"https://penmodding.pm/archives/2483","pic":"../img/hyper.jpg","text":"Featured picture : credit goes to Nix – Name : Hyper Sign – Creator : Nix – Length : Medium – Weight : Heavy – Insert : Yes – Lien : Hyper Sign (FPSB) – Difficulty : Facile", "type":"dc"},'+
'{ "name":"Buster CYL Retractable","link":"https://penmodding.pm/archives/1965","pic":"../img/busterRetr.png","text":"Name : Buster CYL retractable – Creator : Vôre-Tèx – Length : As a buser cyl normal. – Weight : 22 g – Outsert : No – Link : BCYL retractable (upsb) – Difficulty : A bit hard ", "type":"dc"},'+
'{ "name":"Clear Waterfall","link":"https://penmodding.pm/archives/1945","pic":"../img/clearWater.jpg","text":"Nom : Clear Waterfall Mod – Créateur : ? – Taille : 21cm – Poids : 13g – Insert / Ouster  : Oui – Lien : / – Moddage : Facile", "type":"dc"},'+
'{ "name":"Sunrising Spirit","link":"https://penmodding.pm/archives/1905","pic":"../img/sunrising.jpg","text":"Name : Sunrising Spirit – Creator : Neptune – Lenght : 21,3cm – Weigth : 18,6g – Insert : Yes – Link : Sunrising Spirit (FPSB) – Modding : Hard", "type":"dc"},'+
'{ "name":"","link":"","pic":"","text":"", "type":"dc"},'+
'{ "name":"","link":"","pic":"","text":"", "type":"dc"},'+
'{ "name":"","link":"","pic":"","text":"", "type":"dc"},'+
'{ "name":"","link":"","pic":"","text":"", "type":"dc"},'+
'{ "name":"","link":"","pic":"","text":"", "type":"dc"},'+
'{ "name":"","link":"","pic":"","text":"", "type":"dc"},'+
'{ "name":"","link":"","pic":"","text":"", "type":"dc"},'+
'{ "name":"","link":"","pic":"","text":"", "type":"dc"},'+
'{ "name":"","link":"","pic":"","text":"", "type":"dc"},'+
'{ "name":"","link":"","pic":"","text":"", "type":"dc"},'+

'{ "name":"","link":"","pic":"","text":"", "type":"dc"},'+


'{ "name":"Eban Memory DC","link":"https://penmodding.pm/archives/5895","pic":"../img/eban.jpg","text":"Featured picture : credit goes to Eban. – Name : Eban Memory DC – Creator : Unknown, this mod was gifted to Eban by another spinner – Length : 21 cm – Weight : 12 g – Insert : No – Weblink : / – Difficulty : Easy"}]}';