var penmods = '{"mods":[' +
    '{ "name":"KAGAMI DC","link":"https://penmodding.pm/archives/5843","pic":"../img/kagami_dc.jpg","text":"Featured picture : credit goes to Mina. – Name : Kagami DC – Creator : Kagami – Length : 21cm – Weight : 14 g – Insert : No – Difficulty : Medium", "type":"dc"},' +
    '{ "name":"AKAI DC","link":"https://penmodding.pm/archives/5613","pic":"../img/akai_dc.jpg","text":"Featured picture : credit goes to Mina. – Name : Akai DC – Creator : Akai – Length : 22.5 cm – Weight : 13 g – Insert : No – Difficulty : Easy", "type":"dc"},' +
    '{ "name":"IM* Hybrid","link":"https://penmodding.pm/archives/5531","pic":"../img/im hybrid.png","text":"Featured picture : credit goes to Vôre-Tèx – Name : Ivan-Menowa* Hybrid (IM* Hybrid) – Creator : Vôre-Tèx – Length : 22cm – Weight : 22g – Insert : No – Weblink : >Vôre-Tèx blog< – Difficulty :  Medium", "type":"dc"},' +
    '{ "name":"Menowa* Prize Mod","link":"https://penmodding.pm/archives/5574","pic":"../img/menowa prize mod.jpg","text":"Featured picture : credit goes to Mina. – Name : Menowa* Prize Mod – Creator : LostAngelus – Length : 21 cm – Weight : 18.4 g – Insert : No – Difficulty : Easy ", "type":"dc"},' +
    '{ "name":"Nebrask Mod","link":"https://penmodding.pm/archives/5548","pic":"../img/nebrask mod.jpg","text":"Featured picture : credit goes to Ponkotu – Name : Nebrask Mod | note : in Japanese, they call it the Neobaku (neoback?) mod – Creator : Nebrask – Length : 19.5cm – Weight : 16-17g – Insert : No – Weblink : >Ponkotu blog< >Original yt tutorial< – Difficulty :  Easy-Medium", "type":"dc"},' +
    '{ "name":"Bonkura Com.ssa (Comssa)","link":"https://penmodding.pm/archives/5544","pic":"../img/bonkura com.ssa.jpg","text":"Featured picture : credit goes to Vôre-Tèx – Name : Bonkura Com.ssa – Creator : Bonkura – Length : 19.5cm – Weight : 9-10g – Insert : No – Weblink : >Penspinning.fr< – Difficulty :  Super Easy ", "type":"dc"},' +
    '{ "name":"Sonoda Emboss","link":"https://penmodding.pm/archives/5537","pic":"../img/sonoda emboss.jpg","text":"Featured picture : credit goes to Sonoda – Name : Sonoda Emboss mod – Creator : Sonoda – Length : 23cm – Weight : ~20g(?) – Insert : Yes – Weblink : >Sonoda Blog< – Difficulty :  Medium", "type":"dc"},' +
    '{ "name":"ITEZA KT","link":"https://penmodding.pm/archives/5511","pic":"../img/iteza kt.jpg","text":"Featured picture : credit goes to Vôre-Tèx – Name : Iteza KT – Creator : Iteza – Length : 19-20cm – Weight : 14g – Insert : No – Weblink : / – Difficulty :  Super Easy", "type":"dc"},' +
    '{ "name":"MOTSUUN","link":"https://penmodding.pm/archives/5461","pic":"../img/motsuun.jpg","text":"Featured picture : credit goes to Meves (Mizu) – Name : Motsuun – Creator : Meves (Mizu) – Length : 19cm – Weight : Light-medium – Insert : No – Weblink : >Meves Blog< – Difficulty :  Easy", "type":"dc"},' +
    '{ "name":"DR.BT","link":"https://penmodding.pm/archives/5494","pic":"../img/dr.bt.jpg","text":"Featured picture : credit goes to Vôre-Tèx – Name : Dr.BT note : BT is for BinchoTan (stands for charcoal) >wiki explanation< – Creator : Menowa* – Length : 20.5cm – Weight : 19g(?) – Insert : No – Weblink : >Ponkotu blog< – Difficulty :  Super Easy", "type":"dc"},' +
    '{ "name":"Everchix Emboss Mod","link":"https://penmodding.pm/archives/5452","pic":"../img/everchix emboss mod.jpg","text":"Featured picture : credit goes to Everchix – Name : Everchix Emboss Mod (also called EEM) – Creator : Everchix – Length : 22cm(?) – Weight : ~20g(?) – Insert : No – Weblink : / – Difficulty :  Easy~Medium", "type":"dc"},' +
    '{ "name":"Menowa* KT","link":"https://penmodding.pm/archives/5448","pic":"../img/menowakt.png","text":"Featured picture : credit goes to Vôre-Tèx – Name : Menowa* KT (also called “fake KT”) – Creator : Menowa* – Length : 20cm – Weight : ~18g – Insert : No – Weblink : >Menowa* Tumblr < – Difficulty :  Easy", "type":"dc"},' +
    '{ "name":"Menowa* VGG","link":"https://penmodding.pm/archives/5445","pic":"../img/menowa vgg.jpg","text":"Featured picture : credit goes to Vôre-Tèx – Name : Menowa* VGG (also called “fake vicgotgame”) – Creator : Menowa* – Length : 22cm – Weight : ~19g – Insert : No – Weblink : >Ponkotu blog< – Difficulty :  Easy", "type":"dc"},' +
    '{ "name":"Energel St V2","link":"https://penmodding.pm/archives/5436","pic":"../img/energel st v2.png","text":"Featured picture : credit goes to i.suk – Name : Energel ST V2 – Creator : i.suk – Length : 23.7cm – Weight : ~18g – Insert : No – Weblink : >i.suk YT < – Difficulty :  Easy", "type":"dc"},' +
    '{ "name":"Laluteskal Ballsign","link":"https://penmodding.pm/archives/5428","pic":"../img/laluteskal ballsign.jpg","text":"Featured picture : credit goes to Ponkotu – Name : Laluteskal Ballsign – Creator : Laluteskal – Length : 20.5cm – Weight : 17g – Insert : Yes – Weblink : >Ponkotu blog< – Difficulty :  Easy", "type":"dc"},' +
    '{ "name":"Miyana Marvy Marker Mod","link":"https://penmodding.pm/archives/5414","pic":"../img/miyana marvy marker mod.jpg","text":"Featured picture : credit goes to Miyana – Name : Miyana Marvy Marker Mod – Creator : Miyana – Length : 20cm – Weight : ~13g – Insert : No – Weblink : >Miyana blog< note : take a look at this link to see all of Miyana’s MMM – Difficulty :  Easy", "type":"dc"},' +
    '{ "name":"Vore-Tex Kt","link":"https://penmodding.pm/archives/5403","pic":"../img/vore-tex kt.jpg","text":"Featured picture : credit goes to Vôre-Tèx – Name : Vôre-Tèx KT (VT KT) – Creator : Vôre-Tèx – Length : 20cm – Weight : 15-16g – Insert : No – Weblink : >VT blog< – Difficulty :  Medium", "type":"dc"},' +
    '{ "name":"Anpen Mod","link":"https://penmodding.pm/archives/5397","pic":"../img/anpen mod.jpg","text":"Featured picture : credit goes to Menowa* – Name : Anpen mod – Creator : Menowa* – Length : ~22cm – Weight : Heavy (~22g) – Insert : No – Weblink : >Menowa* blog< – Difficulty :  Easy", "type":"dc"},' +
    '{ "name":"Joshin Ballsign","link":"https://penmodding.pm/archives/5343","pic":"../img/joshin ballsign.jpg","text":"Featured picture : credit goes to Joshin – Name : Joshin Ballsign – Creator : Joshin – Length : ~20 cm – Weight : ~14g – Insert : Yes – Weblink : >Joshin blog< – Difficulty : Easy", "type":"dc"},' +
    '{ "name":"Menowa* Mod","link":"https://penmodding.pm/archives/5338","pic":"../img/menowa mod.png","text":"Featured picture : credit goes to Vôre-Tèx – Name : Menowa* mod – Creator : Menowa* – Length : 20 cm – Weight : 20g – Insert : No – Weblink : >Menowa* Tumblr< – Difficulty : Medium", "type":"dc"},' +
    '{ "name":"KZZN Emboss","link":"https://penmodding.pm/archives/5324","pic":"../img/kzzn emboss.jpg","text":"Featured picture : credit goes to KZZN – Name : KZZN Emboss mod – Creator : KZZN – Length : ~22 cm – Weight : >25g – Insert : No – Weblink : >Kzzn Blog< – Difficulty : Easy", "type":"dc"},' +
    '{ "name":"VGG Emboss Mod Replica","link":"https://penmodding.pm/archives/5280","pic":"../img/vgg emboss.jpg","text":"Featured picture : credit goes to Cloud. – Name : VGG emboss mod replica – Creator : Cloud – Length : 24 cm – Weight : ~25 g – Insert : No – Weblink : UPSB (archive), FPSB, VNPSC, PserHome – Difficulty : Medium", "type":"dc"},' +
    '{ "name":"Huwng Kt","link":"https://penmodding.pm/archives/5252","pic":"../img/Huwng kt.png","text":"Featured picture : credit goes to Huwng for the picture. -Name : Huwng KT -Creator : Huwng -Length : 22.5 cm -Weight : 14 g -Outsert : No -Weblink : Huwng YouTube Tutorial -Difficulty : Easy ", "type":"dc"},' +
    '{ "name":"Menowa* Emboss Mod","link":"https://penmodding.pm/archives/5017","pic":"../img/menowa emboss.png","text":"Credit goes to Vôre-Tèx for the featured picture. – Name :Menowa Emboss Mod – Ikusafude – Creator : Menowa* – Length : ~20.5cm – Weight : ~21g – Outsert : No – Weblink : Menowa’s Tumblr, Vôre-Tèx’s YouTube Video – Difficulty : Long and hard", "type":"dc"},' +
    '{ "name":"I.Suk Emboss V3","link":"https://penmodding.pm/archives/4767","pic":"../img/I.Suk emboss v3.jpg","text":"Name : I.suk Emboss V3 – Creator : I.suk – Length : 24.9cm – Weight : 20g – Outsert : No – Weblink : No link – Difficulty : Easy", "type":"dc"},' +
    '{ "name":"PPM Mod","link":"https://penmodding.pm/archives/4761","pic":"../img/ppm.jpg","text":"Featured picture : credit goes to Jing – Name : PPM mod – Creator : PPM – Length : 23.2 cm – Weight : 22 g – Insert : No – Weblink : Youtube – Difficulty : Easy", "type":"dc"},' +
    '{ "name":"Irvine Kt","link":"https://penmodding.pm/archives/4705","pic":"../img/irvine kt.png","text":"Featured picture : credit goes to Vôre-Tèx for the picture and Mjerry56 for the making.  – Name : Irvine KT – Creator : Irvine – Length : 21 cm – Weight : 20 g – Outsert : No – Weblink : Irvine’s blog – Difficulty : Easy", "type":"dc"},' +
    '{ "name":"Shadix Kt","link":"https://penmodding.pm/archives/4046","pic":"../img/shadix kt.jpg","text":"Name : Shadix KT – Creator : Shadix – Length : 20cm – Weight : ~17g – Insert : Yes – Weblink : Pen Meeting place (Japanese) – Difficulty : Easy", "type":"dc"},' +
    '{ "name":"Menowa* Reimei","link":"https://penmodding.pm/archives/4011","pic":"../img/menowareimei.png","text":"Name : Reimei Mod (黎明Mod) – Creator : Menowa – Length : 20cm – Weight : 18g – Insert : Yes – Weblink : Menowa*’s blog, Vôre-Tèx’s blog – Difficulty : Easy but takes time", "type":"dc"},' +
    '{ "name":"Talonplay","link":"https://penmodding.pm/archives/4004","pic":"../img/talonplay.jpg","text":"Name : TalonPlay – Creator : Bonzin – Length : 21cm (?) – Weight : Medium – Outsert : No – Weblink : Saifon’s blog – Difficulty :  Medium", "type":"dc"},' +
    '{ "name":"Night Dc Mod","link":"https://penmodding.pm/archives/3148","pic":"../img/nightz dc mod.jpg","text":"Name : Nightz DC Mod – Creator : Nightz – Length : 20 cm – Weight : ~17 g – Outsert : No – Link : UPSB – Making : Middle", "type":"dc"},' +
    '{ "name":"G-Mod V2","link":"https://penmodding.pm/archives/3190","pic":"../img/g-mod v2.png","text":"Name : G-Mod V2 – Creator :. Gibki – Length : 20cm – Weight :  Medium / Heavy – Insert / Outsert : No – Weblink :. G-Mod V2 (UPSB) – Making : Easy", "type":"dc"},' +
    '{ "name":"J-Vic DC","link":"https://penmodding.pm/archives/3183","pic":"../img/J-Vic dc.jpg","text":"Name : J-Vic DC – Creator : Whizz – Length :  20cm – Weight : about 16g – Outsert : No, but you can add it under the gripcut – Link : UPSB – Making : Middle", "type":"dc"},' +
    '{ "name":"Nautilus Mod","link":"https://penmodding.pm/archives/3131","pic":"../img/nautilus mod.jpg","text":"Name : Nautilus Mod – Creator : BurningFinger – Length : 20,5 cm w/o tips and 22 w/. – Weight : 16 g – Outsert : No – Weblink : UPSB(webarchive), PSH – Modding : Long and very complicated.", "type":"dc"},' +
    '{ "name":"Pom-Pom Mod (Ivabra Pen Mod V2)","link":"https://penmodding.pm/archives/3065","pic":"../img/pom pom mod.jpg","text":"Name : Pom-pom Mod – Creator : Taeko – Length : 21cm – Weight : 20g –  Outsert : No – Weblink : FPSB – Difficulty : Hard", "type":"dc"},' +
    '{ "name":"Inverse Comssa","link":"https://penmodding.pm/archives/3107","pic":"../img/inverse comssa.png","text":"Name : Inverse Comssa – Creator : ? – Length : 18cm – Weight : 12g – Outsert : Why not – Link : UPSB – Difficulty : A little bit hard", "type":"dc"},' +
    '{ "name":"BSNC (BallsignNorisClub)","link":"https://penmodding.pm/archives/2019","pic":"../img/bsnc.jpg","text":"Name : BSNC ( BallsignNorisClub) – Creator : Kr4zy – Length : 21,4 cm – Weight : 13 g – Insert : Yes – Link : / – Difficulty :. Easy", "type":"dc"},' +
    '{ "name":"Ivan Mod (Buster CYL V2)","link":"https://penmodding.pm/archives/3017","pic":"../img/ivan mod.jpg","text":"Name :  Ivan Mod ( Buster Cyl V2) – Creator :  Ivan – Length : 22cm – Weight : 20 g – Outsert : No – Link : Tutoriel Ivan Mod (FPSB) – Making : Medium", "type":"dc"},' +
    '{ "name":"Ivabra Pen Mod","link":"https://penmodding.pm/archives/2963","pic":"../img/ivabra mod.jpg","text":"Name : Ivabra Pen Mod – Creator : Ivabra – Length : 20,5 cm – Weight : ~20 g – Outsert : No – Making : easy", "type":"dc"},' +
    '{ "name":"Killergel Clear","link":"https://penmodding.pm/archives/2966","pic":"../img/KILLERGELCLEARRAINBOW.png","text":"Name : Clear KillerGel – Creator : Taeko – Length : 19,5 cm – Weight : 16 g – Insert  : Yes – Weblink : / – Difficulty : Hard", "type":"dc"},' +
    '{ "name":"Joeys Dc Mod","link":"https://penmodding.pm/archives/2765","pic":"../img/joey dc mod.jpg","text":"Name : Joey’s DC Mod – Creator : Joey – Length : 19,2 cm – Weight : medium – Outsert : No – Link :  Joey’s DC Mod (Youtube) – Modding : Easy.", "type":"dc"},' +
    '{ "name":"Yelo Mod","link":"https://penmodding.pm/archives/2719","pic":"../img/yelo mod.png","text":"Name : Yelo Mod – Creator : Tek – Length : 21 cm – Weight : ~16 g –  Outsert : No – Weblink : Yelo Mod (UPSB v4) – Difficulty : Easy", "type":"dc"},' +
    '{ "name":"Colors Mod","link":"https://penmodding.pm/archives/5832","pic":"../img/colors_mod.jpg","text":"Featured picture : credit goes to Ponkotu – Name : Colors mod – Creator : Slofis – Length : 19.5-20cm – Weight : 15-16g – Insert : No – Weblink : >Ponkotu blog< – Difficulty :  Easy – Stuff : – 2 Color Twin (Barrels, Caps)– 1 Playcolor2 (Backplug)– 1 Old sarasa (Grip)– 1 Supergrip (Grip 2×2)– 2 Old Alpha Gel (Tips) –", "type":"dc"},' +
    '{ "name":"Everchix Comssa","link":"https://penmodding.pm/archives/5877","pic":"../img/everchix_comssa.jpg","text":"Featured picture : credit goes to Mina. – Name : Everchix Comssa – Creator : Everchix – Length : 20.5 cm – Weight : 19 g – Insert : No – Difficulty : Medium", "type":"dc"},' +
    '{ "name":"Orbia Fitline","link":"https://penmodding.pm/archives/5880","pic":"../img/Orbia_fitline.jpg","text":"Featured picture : credit goes to Mina. – Name : Oribia Fitline – Creator : Oribia – Length : 21.5 cm – Weight : 21 g – Insert : No – Difficulty : Medium", "type":"dc"},' +
    '{ "name":"Kacogreen Grip Aviaire (KG GA)","link":"https://penmodding.pm/archives/5855","pic":"../img/kacogreen_grip_aviaire.jpg","text":"Featured picture : credit goes to Mina. – Name : KakoGreen Grip Aviaire (KG GA) – Creator : Megas – Length : 22 cm – Weight : 18 g – Insert : No – Difficulty : Easy", "type":"dc"},' +
    '{ "name":"Vore-Tex Emboss","link":"https://penmodding.pm/archives/5800","pic":"../img/vore-tex_emboss.png","text":"Featured picture : credit goes to Vôre-Tèx – Name : Vôre-Tèx Emboss – Creator : Vôre-Tèx – Length : 20.5cm – Weight : ~16g – Insert : No – Weblink : >Vôre-Tèx blog< – Difficulty :  Medium ", "type":"dc"},' +
    '{ "name":"P4P3RON Mod","link":"https://penmodding.pm/archives/5763","pic":"../img/p4p3ron_mod.jpg","text":"Featured picture : credit goes to Aceron – Name : P4P3RON mod – Creator : Aceron – Length : 20cm – Weight : 11g – Outsert : Yes – Weblink : FPSB V4 – Difficulty :  Easy", "type":"dc"},' +
    '{ "name":"MENOWA* BT VGG","link":"https://penmodding.pm/archives/5677","pic":"../img/Menowa_BT_VGG.jpg","text":"Featured picture : credit goes to Menowa* – Name : Menowa* BT VGG | note : Menowa* calls it the fake VGG charcoal – Creator : Menowa* – Length : 22cm – Weight : Heavy (22g?) – Insert : No – Weblink : Ponkotu blog – Difficulty :  Easy", "type":"dc"},' +
    '{ "name":"Namemory","link":"https://penmodding.pm/archives/2700","pic":"../img/namemory.jpg","text":"Name :. Namemory DC – Creator :. iColor – Length : ~20 cm – Weight : Medium –  Outsert : If you want. – Link : Namemory DC (UPSB) – Difficulty : Easy", "type":"dc"},' +
    '{ "name":"Majora CYL","link":"https://penmodding.pm/archives/2654","pic":"../img/majora.jpg","text":" Name : Majora Cyl – Creator : Majora – Length : 23 cm – Weight : 22 g – Outsert : No – Link : Majora CYL (GPC) – Difficulty : Easy ", "type":"dc"},' +
    '{ "name":"Stek Body","link":"https://penmodding.pm/archives/1110","pic":"../img/stek.png","text":"Ceci est une technique de Tek. Ce n’est pas réelement un mod mais plutôt une technique de moddage permettant de “colorer” un peu plus le mod. Cette technique peut être appliquable à : – Com.Ssa – Bellcolor Mod – BusterCYL – Tout les autres mods qui ont pour corps un", "type":"dc"},' +
    '{ "name":"CYL 83 Mod","link":"https://penmodding.pm/archives/1108","pic":"../img/cyl 83.jpg","text":"Featured picure : credit goes to olllDumPlllo.   – Name : Cyl 83 Mod ( Tek’s Super Tip Mod ) – Creator : olllDumPlllo – Length : 21 cm – Weight : Medium – Outsert : No – Link : Cyl 83 Mod ( ThaiSpinner ) – Difficulty : Easy", "type":"dc"},' +
    '{ "name":"Pirat KS aka Stuhl mod","link":"https://penmodding.pm/archives/2584","pic":"../img/stuhl.jpg","text":"Name : Pirat KS – Creator : Stuhl – Length : Long – Weight : Middle –  Outsert : No – Link : / – Difficulty :  Easy-Medium", "type":"dc"},' +
    '{ "name":"Hyper Sign","link":"https://penmodding.pm/archives/2483","pic":"../img/hyper.jpg","text":"Featured picture : credit goes to Nix – Name : Hyper Sign – Creator : Nix – Length : Medium – Weight : Heavy – Insert : Yes – Lien : Hyper Sign (FPSB) – Difficulty : Facile", "type":"dc"},' +
    '{ "name":"Buster CYL Retractable","link":"https://penmodding.pm/archives/1965","pic":"../img/busterRetr.png","text":"Name : Buster CYL retractable – Creator : Vôre-Tèx – Length : As a buser cyl normal. – Weight : 22 g – Outsert : No – Link : BCYL retractable (upsb) – Difficulty : A bit hard ", "type":"dc"},' +
    '{ "name":"Clear Waterfall","link":"https://penmodding.pm/archives/1945","pic":"../img/clearWater.jpg","text":"Nom : Clear Waterfall Mod – Créateur : ? – Taille : 21cm – Poids : 13g – Insert / Ouster  : Oui – Lien : / – Moddage : Facile", "type":"dc"},' +
    '{ "name":"Sunrising Spirit","link":"https://penmodding.pm/archives/1905","pic":"../img/sunrising.jpg","text":"Name : Sunrising Spirit – Creator : Neptune – Lenght : 21,3cm – Weigth : 18,6g – Insert : Yes – Link : Sunrising Spirit (FPSB) – Modding : Hard", "type":"dc"},' +
    '{ "name":"Comatic Mod","link":"https://penmodding.pm/archives/1900","pic":"../img/comatic.jpg","text":"Name : Comatic – Creator : Gecko3600 – Lenght :  21.9 cm(superpirat body), 22.8 cm (dong_a body) – Weigth : 15,4g – Outsert : No. – Link : Comatic (FPSB) – Modding : A bit hard.", "type":"dc"},' +
    '{ "name":"Flying Panda","link":"https://penmodding.pm/archives/1855","pic":"../img/flying panda.jpg","text":"Featured picture : credit goes to ??? – Name : Flying Panda Mod – Creator : ? – Length : 21,5 cm – Weight : ~16 g – Outsert : No – Link : ? – Difficulty : Easy ", "type":"dc"},' +
    '{ "name":"Coulomb Namae Mod","link":"https://penmodding.pm/archives/1851","pic":"../img/couloumb namae mod.png","text":"Featured picture : credit goes to TEK – Name : Coulomb Namae Mod – Creator : Coulomb – Length : 19.5 cm – Weight : Light – Outsert : No – Weblink: No link. – Difficulty : Easy", "type":"dc"},' +
    '{ "name":"Minovate DC","link":"https://penmodding.pm/archives/1847","pic":"../img/minovate dc.png","text":"Featured picture : credit goes to TEK – Name : Minovate DC – Creator : Minwoo – Length : 20, 5 cm – Weight :  15g –  Outsert : No – Webink : Minovate DC (UPSB) – Difficulty : Easy", "type":"dc"},' +
    '{ "name":"Zolty Mod","link":"https://penmodding.pm/archives/1825","pic":"../img/zolty mod.jpg","text":"Featured picture : credit goes to ??? – Name : Zółty Mod – Creator : Pari – Length : 20 cm – Weight : 16 g – Outsert : Why not =) – Weblink : Zółty Mod (Youtube) – Difficulty : Easy ", "type":"dc"},' +
    '{ "name":"Dr. KT Mechanical Pencil","link":"https://penmodding.pm/archives/1800","pic":"../img/drkt mechanical.jpg","text":"Featured picture : credit goes to KunLin – Name : Dr.Kt MP – Creator : KunLin – Length : As a Dr.kt – Weight : A bit heavier than a Dr.Kt. –  Outsert : Yes – Link : Dr.Kt Mechanical Pencil (UPSB) – Difficulty : Long and hard.", "type":"dc"},' +
    '{ "name":"The Breaker","link":"https://penmodding.pm/archives/1631","pic":"../img/the breaker.jpg","text":"Name : The Breaker – Creator : Guitrium – Length : from 11 to 21 cm –  Weigtht : 15 g – Insert : Yes – Link : The Breaker (UPSB) – Difficulty : Hard ", "type":"dc"},' +
    '{ "name":"8Namae Mod","link":"https://penmodding.pm/archives/1600","pic":"../img/8namae mod.jpg","text":"Name : 8Namae Mod – Creator : Gollumsk8 – Lenght : 21 cm –  Weight: 19 g – Insert / Outsert : No. – Lien : 8Namae Mod (FPSB) – Difficulty : Easy.", "type":"dc"},' +
    '{ "name":"BSKT (BALLSIGN.KT)","link":"https://penmodding.pm/archives/1578","pic":"../img/bskt.jpg","text":"Name : BSKT (BallSign.KT) – Creator : Bonkura – Length : 17 cm – Weight :  7 g – Insert / Outsert : No – Link : BSKT (Pen’s Meeting Place) – Difficulty : Facile Easy", "type":"dc"},' +
    '{ "name":"EX2 Mod","link":"https://penmodding.pm/archives/1569","pic":"../img/ex2.jpg","text":"Name : EX2 – Creator : iMatt – Length : 19 cm – Weight :Ryo Cheat Comssa < EX2 < Dr. KT – Insert / Outsert : No – Link : EX2 (UPSB) – Difficulty : Medium", "type":"dc"},' +
    '{ "name":"Riason Dc Mod","link":"https://penmodding.pm/archives/1565","pic":"../img/riason.jpg","text":"Name : RiAsON DC Mod (not the official name) – Creator : ? – Length : 21.5 cm – Weight : 12 g – Insert / Outsert : No – Link : RiAsON DC Mod (Pen’s Meeting place) – Difficulty : Easy", "type":"dc"},' +
    '{ "name":"Play Color 2 Mod (Zyavuxa Mod)","link":"https://penmodding.pm/archives/1513","pic":"../img/pc2.jpg","text":"Name : PlayColor 2 Mod (ZYAVUXA Mod) – Creator : ? – Length : 21 cm – Weight : 12 g – Insert / Outsert : No – Link : PLAY COLOR 2 Mod (Pen’s Meeting Place) – Difficulty : Easy ", "type":"dc"},' +
    '{ "name":"Strike Ex","link":"https://penmodding.pm/archives/1481","pic":"../img/strike.jpg","text":"Name : Strike eX – Creator : wcy – Lenght : Unknown – Weigth : Heavy – Outsert : Electric tape  (One white and another color) – Link : Strike eX (HKPSA) – Modding : Easy", "type":"dc"},' +
    '{ "name":"BBS","link":"https://penmodding.pm/archives/1479","pic":"../img/bbs.jpg","text":" Name : BBS Mod – Creator : Tushix – Length : 11 – 23 cm – Weight : Light – Insert : Yes – Link : BBS Mod (UPSB) – Modding : Easy", "type":"dc"},' +
    '{ "name":"Marvy Marker Mod","link":"https://penmodding.pm/archives/1475","pic":"../img/mmm.jpg","text":"Name : Marvy Marker Mod – Creator : Skymask – Lenght : 19,6 cm – Weigth : 10.4 g – Outsert : No – Link : Marvy Marker Mod (Pen’s meeting place) – Modding :  Easy", "type":"dc"},' +
    '{ "name":"VicGotGame Mod","link":"https://penmodding.pm/archives/1443","pic":"../img/vgg.jpg","text":"Name : Vicgotgame Mod – Creator : Vicgotgame – Length : Custom – Weight : I think over 20g – Outsert : No – Link : Vicgotgame Mod ( UPSB ) – Making : Medium", "type":"dc"},' +
    '{ "name":"Baaron SC Mod","link":"https://penmodding.pm/archives/1420","pic":"../img/baaronsc.jpg","text":"Name : Baaron’s SC Mod – Creator : Baaron – Length : 20.5 cm – Weight : 14 g – Outsert : Baaron put some chatterton. – Link : Baaron’s SC Mod (UPSB) – Modding : Easy", "type":"dc"},' +
    '{ "name":"BSPC (Ballsign Playcolor)","link":"https://penmodding.pm/archives/1349","pic":"../img/bspc.jpg","text":"Name : Ballsing Playcolor (BSPC) – Creator : Unknown – Length : 21 cm – Weight : 12 g – Insert : Yes – Link : BSPC (Pen’s meeting place) – Modding : Easy ", "type":"dc"},' +
    '{ "name":"Seven Sweet Drop Mod","link":"https://penmodding.pm/archives/1330","pic":"../img/sevensweetdrop.jpg","text":"Name : Sweet Drop Mod (SEVEN’s version) – Creator : SEVEN – Length : 20 cm – Weight : 12 g –  Outsert : No – Link : Sweet Drop Mod (SEVEN’s version) (Ponkotu blog) – Making : Middle", "type":"dc"},' +
    '{ "name":"Sweet Drop Mod","link":"https://penmodding.pm/archives/1326","pic":"../img/sweetdropmod.jpg","text":"Name : Sweet Drop Mod – Creator : Unknown – Lenght : 20 cm – Weigth : 16 g – Outsert : No – Link : Sweet Drop Mod ( Ponkotu’s blog ) – Making : Easy", "type":"dc"},' +
    '{ "name":"Comprecise","link":"https://penmodding.pm/archives/1317","pic":"../img/comprecise.jpg","text":"Name : ComPrecise – Creator : Tone – Lenght : 20.5 cm – Weigth : 16g – Insert / Outsert : No. – Link : ComPrecise (UPSB) – Modding : Easy", "type":"dc"},' +
    '{ "name":"Seven Watercolor Mod","link":"https://penmodding.pm/archives/1225","pic":"../img/sevenwatercolor.png","text":"Name : Seven’s Watercolor Mod – Creator : Seven – Lenght : 19,4 cm – Weight : ~16 g – Outsert : No. – Link : Seven’s Watercolor Mod ( UPSB ) – Making : Easy", "type":"dc"},' +
    '{ "name":"Emboss Mod","link":"https://penmodding.pm/archives/1105","pic":"../img/emboss mod.JPG","text":"Nom : Emboss Mod – Créateur : ? – Taille : 21 cm – Poids : 16 g – Insert / Outsert : Non – Lien : Emboss Mod ( Blog de ponkotu ), Emboss Mod ( FPSB ) – Moddage : Facile ", "type":"dc"},' +
    '{ "name":"Dr. KT","link":"https://penmodding.pm/archives/16","pic":"../img/drkt.jpg","text":"Name : Dr.Kt – Creator : Ryo – Length : 20.5 cm – Weight : 20 g – Outsert : Yes – Link : Dr.Kt and others… – Making : Easy", "type":"dc"},' +
// SC MODS   
   
    '{ "name":"Blue Droplet","link":"https://penmodding.pm/archives/5828","pic":"../img/blue drop.jpg","text":"Featured picture : credit goes to Vain – Name : Blue Droplet – Creator : Vain – Length : 19.5cm – Weight : 13g? – Insert : Yes – Weblink : >Vain blog< – Difficulty :  Medium ", "type":"sc"},' +
    '{ "name":"Flare Vain G3","link":"https://penmodding.pm/archives/5824","pic":"../img/flare vain.jpg","text":"Featured picture : credit goes to Vain – Name : Flare Vain G3 – Creator : Vain – Length : 19.5cm – Weight : 13g – Insert : Yes – Weblink : >Vain YT< – Difficulty :  Medium", "type":"sc"},' +
    '{ "name":"RSVP MX V2","link":"https://penmodding.pm/archives/5794","pic":"../img/rsvp v2.png","text":"Featured picture : credit goes to Vôre-Tèx – Name : RSVP MX V2 – Creator : Vôre-Tèx – Length : 19cm – Weight : 1g heavier than regular MX – Insert : Yes – Weblink : >Vôre-Tèx blog< – Difficulty :  Super Easy", "type":"sc"},' +
    '{ "name":"Itezy-3","link":"https://penmodding.pm/archives/5747","pic":"../img/itezy-3.jpg","text":"Featured picture : credit goes to Iteza – Name : Itezy-3 – Creator : Iteza – Length : 20cm – Weight : 14g – Insert : Yes – Weblink : >Iteza YT< – Difficulty :  Easy", "type":"sc"},' +
    '{ "name":"Monacho G3 Mod","link":"https://penmodding.pm/archives/5741","pic":"../img/monacho.jpg","text":"Featured picture : credit goes to Saifon – Name : Monacho G3 mod – Creator : Monacho – Length : 19.5cm? – Weight : ~10g – Insert : Yes – Weblink : >Ponkotu blog < – Difficulty :  Easy-Medium", "type":"sc"},' +
    '{ "name":"Vore-Tex G3 Mod","link":"https://penmodding.pm/archives/5720","pic":"../img/vore tex g3.jpg","text":"Featured picture : credit goes to Vôre-Tèx – Name : Vôre-Tèx G3 mod – Creator : Vôre-Tèx – Length : 20cm – Weight : 15.5g – Insert : Yes – Weblink : >Vôre-Tèx YT < FPSB V4 – Difficulty :  Easy-Medium", "type":"sc"},' +
    '{ "name":"Menowa* Air G3","link":"https://penmodding.pm/archives/5695","pic":"../img/menowa air g3.jpg","text":"Featured picture : credit goes to Menowa* Tutorial translated from Japanese to English by >Skadi<. Huge thank him. – Name : Menowa* Air G3 – Creator : Menowa* – Length : 20cm(?) – Weight :  About 14g – Insert : Yes – Weblink : >Menowa YT< – Difficulty :  Hard and long", "type":"sc"},' +
    '{ "name":"RSVP MX Mechanical","link":"https://penmodding.pm/archives/5653","pic":"../img/rsvp mx mechanical pencil.png","text":"Featured picture : credit goes to Vôre-Tèx – Name : RSVP MX Mechanical Pencil (RSVP MX MP) – Creator : Vôre-Tèx – Length : 19cm – Weight : 14g – Insert : Yes – Weblink : >Vôre-Tèx blog< – Difficulty :  Easy-Medium", "type":"sc"},' +
    '{ "name":"VT MX","link":"https://penmodding.pm/archives/5647","pic":"../img/vt mx.jpg","text":"Featured picture : credit goes to Vôre-Tèx – Name : Vôre-Tèx RSVP MX (or VT MX) – Creator : Vôre-Tèx – Length : 20cm – Weight : 14g – Insert : Yes – Weblink : >Vôre-Tèx blog< – Difficulty :  Easy-Medium", "type":"sc"},' +
    '{ "name":"Mesi G3 V4","link":"https://penmodding.pm/archives/5641","pic":"../img/mesi g3.jpg","text":"Featured picture : credit goes to Mesi – Name : Mesi G3 mod V4 – Creator : Mesi – Length : 20cm? – Weight : Medium – Insert : Yes – Weblink : >Mesi blog< – Difficulty :  Medium", "type":"sc"},' +

    '{ "name":"Iroziro G3 Mod","link":"https://penmodding.pm/archives/5575","pic":"../img/iroziro.jpg","text":"Featured picture : credit goes to Saifon – Name : Iroziro G3 mod – Creator : Iroziro – Length : 19cm – Weight : Medium – Insert : Yes – Weblink : >Ponkotu’s blog< – Difficulty :  Easy-Medium", "type":"sc"},' +
    '{ "name":"Centi G3 Mod","link":"https://penmodding.pm/archives/5565","pic":"../img/centi g3.jpg","text":"Featured picture : credit goes to Saifon – Name : ceNti G3 mod – Creator : ceNti – Length : 20cm – Weight : 15? – Insert : Yes – Weblink : >Ponkotu blog< – Difficulty :  Medium", "type":"sc"},' +
    '{ "name":"Hibachi Mod V1","link":"https://penmodding.pm/archives/5512","pic":"../img/hibachi mod.jpg","text":"Featured picture : credit goes to Hibachi – Name : Hibachi mod (also called Akashiya mod) – Creator : Hibachi – Length : 20cm(?) – Weight : ~16g(?) – Insert : No – Weblink : >Hibachi blog< – Difficulty :  Medium", "type":"sc"},' +
    '{ "name":"Coffeelucky MX","link":"https://penmodding.pm/archives/5501","pic":"../img/coffeelucky mx.jpg","text":"Featured picture : credit goes to Coffeelucky – Name : Coffeelucky MX – Creator : Coffeelucky – Length : 19.8cm – Weight : 14g – Insert : Yes – Weblink : >Coffeelucky Instagram< – Difficulty :  Super Easy", "type":"sc"},' +
    '{ "name":"Watto G3 Mod","link":"https://penmodding.pm/archives/5470","pic":"../img/watto g3.jpg","text":"Featured picture : credit goes to Vôre-Tèx – Name : Watto G3 Mod – Creator : Watto – Length : ~20cm – Weight : ~14g – Insert : No – Weblink : >Kzzn blog< – Difficulty :  Complex", "type":"sc"},' +
    '{ "name":"Refine G3 Mod","link":"https://penmodding.pm/archives/5387","pic":"../img/refine g3.jpg","text":"Featured picture : credit goes to Ponkotu – Name : refine G3 mod – Creator : refine – Length : ~19 cm – Weight : Light – Insert : Yes – Weblink : >refine blog< – Difficulty : Very easy", "type":"sc"},' +
    '{ "name":"Eban G3 Mod","link":"https://penmodding.pm/archives/5381","pic":"../img/eban g3.jpg","text":"Featured picture : credit goes to Ponkotu – Name : Eban G3 mod – Creator : Eban – Length : ~20 cm – Weight : Light~medium – Insert : Yes – Weblink : >Ponkotu blog< – Difficulty : Easy-Medium", "type":"sc"},' +
    '{ "name":"Fukrou G3 V2","link":"https://penmodding.pm/archives/5373","pic":"../img/fukro2.jpg","text":"Featured picture : credit goes to Fukrou – Name : Fukrou G3 (V2?) – Creator : Fukrou – Length : ~20 cm – Weight : Light~medium – Insert : Yes – Weblink : >Fukrou blog< – Difficulty : Easy-Medium", "type":"sc"},' +
    '{ "name":"Fukrou G3 V1","link":"https://penmodding.pm/archives/5364","pic":"../img/fukro1.jpg","text":"Featured picture : credit goes to Fukrou – Name : Fukrou G3 (V1?) – Creator : Fukrou – Length : ~20 cm – Weight : Light~medium – Insert : Yes – Weblink : >Fukrou blog< – Difficulty : Easy-Medium", "type":"sc"},' +
    '{ "name":"Malimo G3","link":"https://penmodding.pm/archives/5353","pic":"../img/malimo.jpg","text":"Featured picture : credit goes to Malimo – Name : Malimo G3 – Creator : Malimo – Length : ~20 cm? – Weight : ~14g? – Insert : Yes – Weblink : >Malimo blog< – Difficulty : Easy-Medium", "type":"sc"},' +

    '{ "name":"41rflow G3 Mod","link":"https://penmodding.pm/archives/5305","pic":"../img/4airflow.jpg","text":"Featured picture : credit goes to Vôre-Tèx – Name : 41RFLOW G3 mod – Creator : Vôre-Tèx – Length : 20 cm – Weight : 14g – Insert : Yes – Weblink : / – Difficulty : Medium", "type":"sc"},' +
    '{ "name":"400¥ G3","link":"https://penmodding.pm/archives/4730","pic":"../img/400yen.jpg","text":"Featured picture : credit goes to Vôre-Tèx for the picture.  – Name : 400¥ G3 – Creator : Vôre-Tèx – Length : 21 cm – Weight : 14 g – Insert : Yes – Weblink : Vôre-Tèx Twitter – Difficulty : Easy ", "type":"sc"},' +
    '{ "name":"Beige G3","link":"https://penmodding.pm/archives/4715","pic":"../img/beige.jpg","text":"Featured picture : credit goes to Beige. – Name : Beige G3 mod – Creator : Beige – Length : 20 cm – Weight : 14 g – Insert : Yes – Weblink : Beige’s blog – Difficulty : Easy", "type":"sc"},' +
    '{ "name":"Vain G*2","link":"https://penmodding.pm/archives/4661","pic":"../img/vain g2.jpg","text":"Featured picture : credit goes to the website ペンたちの集会所 – Name : Vain G*2 – Creator : Vain – Length : Medium – Weight : Medium – Insert : Yes – Weblink : Pen’s meeting place (Japanese) – Difficulty : Easy ", "type":"sc"},' +
    '{ "name":"DI*Vain","link":"https://penmodding.pm/archives/4653","pic":"../img/divain.jpg","text":"Featured picture : credit goes to Vain – Name : Di*Vain – Creator : Vain – Length : ~20.5 cm – Weight : ~17g – Insert : Yes – Weblink : Vain’s blog – Difficulty : Easy", "type":"sc"},' +
    '{ "name":"Reamtea G3","link":"https://penmodding.pm/archives/4035","pic":"../img/reamtea.jpg","text":"Name : Reamtea G3 – Creator : Reamtea – Length : 19.5cm – Weight : 14g (?) – Insert : Yes – Weblink : Pen Meeting place (Japanese) – Difficulty : Easy", "type":"sc"},' +
    '{ "name":"Cafca G3","link":"https://penmodding.pm/archives/4024","pic":"../img/cafca.jpg","text":"Name : Cafca G3 – Creator : Cafca – Length : 20cm – Weight : 14g (?) – Insert : Yes – Weblink : Pen Meeting place (Japanese) – Difficulty : Easy", "type":"sc"},' +
    '{ "name":"Mesi G3 Mod V2","link":"https://penmodding.pm/archives/3348","pic":"../img/mesiv2.png","text":"This Mesi G3 mod v2 was made by MJerry. All credits go to him.   First JeB penmod tutorial on my website, the Mesi v2 ! I found it on >Mesi’s blog<", "type":"sc"},' +
    '{ "name":"Hibachi Mod","link":"https://penmodding.pm/archives/3243","pic":"../img/hibachi.jpg","text":"Name : Hibachi Mod – Creator : Hibachi – Length : 21cm – Weight : Medium – Outsert : No – Weblink : Pen’s meeting place – Making : Complicated and super haaard", "type":"sc"},' +
    '{ "name":"Rec.Modrod","link":"https://penmodding.pm/archives/3164","pic":"../img/rec modrod.png","text":"Name : Rec.ModRod – Creator: LNT_Phat – Length : 21 cm – Weight : about 15g – Insert : Yes – Weblink Rec.ModRod (UPSB) – Difficulty :  Easy", "type":"sc"},' +

    '{ "name":"Trinity Mod","link":"https://penmodding.pm/archives/3087","pic":"../img/trinity.jpg","text":"Name : Trinity Mod – Creator : James[PSH] – Length : 21,8cm – Weight : Maybe a little bit more than BusterCYL – Insert : Yes – Link : UPSB – Difficulty : Long and hard", "type":"sc"},' +
    '{ "name":"Nachoaddict SC Mod","link":"https://penmodding.pm/archives/2917","pic":"../img/nachoaddict sc.jpg","text":"Name : Nachoaddict SC Mod – Creator : Nachoaddict – Length : 20.5cm – Weight :  Medium – Outsert : Maybe Eletrical tape – Weblink : Nachoaddict SC mod (UPSB) – Difficulty : Hard ", "type":"sc"},' +
    '{ "name":"Flexcyl MX","link":"https://penmodding.pm/archives/2903","pic":"../img/flexcyl.jpg","text":"Name : Flexcyl mx – Creator : Taeko – Length : 20cm – Weight : 13g –  Outsert : Why not – Link : Flexcyl Mx (FPSB) – Difficulty : Easy", "type":"sc"},' +
    '{ "name":"Product SC Mod","link":"https://penmodding.pm/archives/2849","pic":"../img/product sc.jpg","text":"Name : Product SC Mod – Creator : Product (?) – Length : 19,5 cm – Weight : 12 g – Outsert : No – Link : Product SC Mod (THPSC) – Difficulty : Easy", "type":"sc"},' +
    '{ "name":"Limit G3 Mod","link":"https://penmodding.pm/archives/2771","pic":"../img/limit g3.jpg","text":"Name : Limit G3 Mod – Creator : LIMIT – Length : 19.5cm – Weight : Moyen – Insert : Yes – Link : Limit G3 Mod (UPSB V4)(wayback) – Difficulty : Facile", "type":"sc"},' +
    '{ "name":"Syrti G3 Mod","link":"https://penmodding.pm/archives/2750","pic":"../img/syrti g3.png","text":"Name : Syrti’s G3 Mod – Creator : Syrti – Length : 20cm – Weight : 13g – Insert : Yes – Link : Syrti G3 (GPC)(pic are ded) – Difficulty : Long", "type":"sc"},' +
    '{ "name":"RSVP ST","link":"https://penmodding.pm/archives/2745","pic":"../img/rsvp st.jpg","text":"Name : RSVP ST – Creator : BLIN – Length : ~ 20,5 cm – Weight : Medium – Insert : Yes – Link : RSVP ST (UPSB)(wayback) – Difficulty: A little bit hard", "type":"sc"},' +
    '{ "name":"Saizen RSVP Mod","link":"https://penmodding.pm/archives/1441","pic":"../img/saizen rsvp mod.jpg","text":"Name : Saizen RSVP Mod – Creator : Saizen – Length : Short – Weight : MoyenMedium – Insert  : Yes – Link : Saizen RSVP Mod (UPSB) [cf Baaron’s post] – Difficulty : Easy-Medium", "type":"sc"},' +
    '{ "name":"Outsider G3 Mod","link":"https://penmodding.pm/archives/2707","pic":"../img/outsider.png","text":"Name : Outsider G3 Mod – Creator : Outsider – Length : Medium – Weight : Medium – Insert : Yes – Link : Outsider G3 Mod (UPSB) – Difficulty : Easy", "type":"sc"},' +
    '{ "name":"ANY-X","link":"https://penmodding.pm/archives/2695","pic":"../img/any-x.jpg","text":"Name : Any-X – Creator : Zaazu – Length : 19 cm – Weight : 12 g – Insert / Outsert : Why not. – Link : Any-X (GPC) – Difficulty : Medium", "type":"sc"},' +

    '{ "name":"Migi G3 Mod","link":"https://penmodding.pm/archives/2643","pic":"../img/migi G3.jpg","text":"Featured picture : credit goes to Migi – Name : Migi G3 Mod – Creator : Migi – Length : 20.5cm – Weight : 15.5g – Insert : Yes – Link : Migi G3 mod (GPC) – Difficulty : Medium", "type":"sc"},' +
    '{ "name":"G3 MX - Writeable","link":"https://penmodding.pm/archives/2627","pic":"../img/g3 mx.jpg","text":"Featured picture : credit goes to Whizz – Name : Writable G3 Mx – Creator : whizz – Length : As a G3 Mx – Weight : A little bit more than G3 Mx – Insert : Yes – Link : G3 Mx rétractable (UPSB V3) – Dificulty : Medium", "type":"sc"},' +
    '{ "name":"Onyx","link":"https://penmodding.pm/archives/2619","pic":"../img/onyx.jpg","text":"Featured picture : credit goes to Onyx-07 – Name : Onyx Mod – Creator : Onyx-o7 – Length : As an RSVP mx – Weight : As an Mx² – Insert  : Yes – Link : Onyx Mod (UPSB v3) – Difficulty : Easy", "type":"sc"},' +
    '{ "name":"FG3 Mod","link":"https://penmodding.pm/archives/2597","pic":"../img/fg3.jpg","text":"Featured picture : credit goes to Whizz – Name : FG3 mod – Creator : whizz – Length : 19cm – Weight : 17g – Insert : Yes – Weblink : FG3 Mod (UPSB v3) – Difficulty : Easy", "type":"sc"},' +
    '{ "name":"Ajisai SC Mod","link":"https://penmodding.pm/archives/2592","pic":"../img/ajisai sc.jpg","text":"Featured picture : credit goes to Whizz note : I think this one is not the legit tutorial. – Name : Ajisai’s SC mod – Creator : Ajisai – Length : Medium", "type":"sc"},' +
    '{ "name":"Buhryan Mod","link":"https://penmodding.pm/archives/2536","pic":"../img/buhryan.jpg","text":"Name : Buhryan Mod – Creator : Buhryan – Length: 21cm – Weight: 17g – Outsert : No – Likn : Buhryan Mod (UPSB v3) – Difficulty : Long", "type":"sc"},' +
    '{ "name":"Hybrid Geraser Mod","link":"https://penmodding.pm/archives/2508","pic":"../img/hybrid geraser.jpg","text":"Featured picture : credit goes to Taeko – Name : Hybrid Geraser Mod – Creator : Taeko – Length: 20 cm – Weight: 16 g – Insert : Yes – Link : Hybrid Geraser Mod (FPSB) – Difficulty : Middle", "type":"sc"},' +
    '{ "name":"Sausage Mod","link":"https://penmodding.pm/archives/2491","pic":"../img/sausage.jpg","text":"Featured picture : credit goes to Whizz – Name : Sausage mod – Creator : whizz  – Length : 19,7 cm – Weight : ~15 g – Insert : No – Link : Sausage mod (UPSB) – Difficulty : Easy", "type":"sc"},' +
    '{ "name":"Fr. Seven Mod","link":"https://penmodding.pm/archives/2476","pic":"../img/fr seven.jpg","text":"Nom :Fr.Seven Mod – Créateur : Nix – Taille : Comme un Seven Mod, soit 20 cm – Poids : ~  16g – Insert / Outsert : Oui – Lien : FR.Seven Mod (FPSB) – Moddage : Facile", "type":"sc"},' +
    '{ "name":"Impact Gel","link":"https://penmodding.pm/archives/2222","pic":"../img/impact.jpg","text":"Featured picture : credit goes to Hybrya –  Name : Impact’Gel – Creator : Hybrya – Length :  19 cm – Weight :  19 g – Insert: Yes – Link : Impact Gel (FPSB) – Difficulty : Hard ", "type":"sc"},' +

    '{ "name":"Grizzly Mod","link":"https://penmodding.pm/archives/2018","pic":"../img/grizzly.png","text":"Name : Grizzly – Creator : Nos635 – Length : 20 cm – Weight : As a Waterfall mod – Insert : Yes – Link : Grizzly (FPSB) – Difficulty : Difficult ", "type":"sc"},' +
    '{ "name":"Superbroad Mod","link":"https://penmodding.pm/archives/2004","pic":"../img/superbroad.jpg","text":"Name : Superbroad – Creator : Mot – Lenght : 21 cm – Weigth : 19 g – Insert : Yes – Link : Superbroad (FPSB) – Difficulty : Very long", "type":"sc"},' +
    '{ "name":"Animal G3","link":"https://penmodding.pm/archives/1932","pic":"../img/animal g3.bmp","text":"Name : Animal G3 Mod – Creator : An[!]Mal – Length : 20,6 cm – Weight : 18 g – Insert: Yes – Link : Animal G3 Mod (FPSB) – Difficulty : A bit hard", "type":"sc"},' +
    '{ "name":"Sakura Evolution","link":"https://penmodding.pm/archives/1934","pic":"../img/sakura.jpg","text":"Name : Sakura’s Evolution – Creator : Hybrya – Lenght : 20 cm –  Weigth : 15 g – Insert: Yes – Link : Sakura’ s Evolution (FPSB) – Modding : Middle", "type":"sc"},' +
    '{ "name":"Pk G3 Mod (Love Mod)","link":"https://penmodding.pm/archives/1921","pic":"../img/pk g3.jpg","text":"Name : PK G3 Mod (Love mod) – Creator : Peda – Lenght : 21 cm – Weigth : 18,5 g – Insert : Yes – Link : PK G3 Mod (FPSB) – Modding : A bit hard ", "type":"sc"},' +
    '{ "name":"G2 CTE Evolved","link":"https://penmodding.pm/archives/1877","pic":"../img/g2cte.jpg","text":"Name : G2-CTE Evolved – Creator : +Guitrum+ – Lenght : 20-21cm – Weigth : Heavy – Insert / Outsert : Yes – Linki : G2-CTE Evolved (UPSB v3) – Modding : Hard, long.", "type":"sc"},' +
    '{ "name":"K7 Hybrid","link":"https://penmodding.pm/archives/1869","pic":"../img/k7hybrid.jpg","text":"Featured picture : credit goes to imatt – Name : K7 Hybrid – Craator : iMatt – Length : 19.5 cm – Weight : Middle – Insert : Yes – Link : K7 Hybrid (UPSB v3) – Modding : A bit hard.", "type":"sc"},' +
    '{ "name":"Evo Sunburst","link":"https://penmodding.pm/archives/1863","pic":"../img/evo sunburst.jpg","text":"Featured picture : credit goes to Pari – Name : Sunburst Evolution (aka Evo Sunburst) – Creator : Pari – Lenght : 20.5 cm – Weigth : 15g – Insert : Yes – Link : Evo Sunburst (UPSB v3) – Modding : A bit hard", "type":"sc"},' +
    '{ "name":"Single Grip Maniac Retract","link":"https://penmodding.pm/archives/1858","pic":"../img/single grip.jpg","text":"Featured picture : credit goes to NxxS – Name : Single Grip Maniac Retract – Creator : NxxS – Length : 19.7 cm – Weight : 15 g – Insert: Yes – WebLink : Single Grip Maniac Retract (FPSB) – Difficulty : Middle", "type":"sc"},' +
    '{ "name":"Nachoaddict Mp Mod","link":"https://penmodding.pm/archives/1840","pic":"../img/nachomp.jpg","text":"Featured picture : credit goes to Nachoaddict – Name : Nachoaddict’s MP Mod (TBA) – Creator : Nachoaddict – Length : 21cm – Weight : Middle – Outsert : No – Weblink : TBA (UPSB v4) – Difficulty : Hard", "type":"sc"},' +

    '{ "name":"Flex G3 Lavable","link":"https://penmodding.pm/archives/1699","pic":"../img/flexg3.jpg","text":"Name : Flex G3 lavable – Creator : F1r3fly – Lenght : 20 cm – PWeigth : 12 g – Insert / Outsert : Yes – Link : Flex G3 Lavable – Modding : A bit hard", "type":"sc"},' +
    '{ "name":"RSVP AMX","link":"https://penmodding.pm/archives/1690","pic":"../img/rsvpamx.jpg","text":"Name : RSVP AMX – Creator : ? – Lenght : 19 cm – Weigth : 12 g – Insert : Yes – Link : RSVP AMX (PenSpinning Museum) – Modding : Easy", "type":"sc"},' +
    '{ "name":"Glenn Matthews","link":"https://penmodding.pm/archives/1674","pic":"../img/glenn.png","text":"Name : Glenn Matthews – Creator : Purplet – Lenght : 20.5 cm – Weigth : 18 g – Insert : Yes – Link : Glenn Matthews (UPSB) – Moddaing : Dificult", "type":"sc"},' +
    '{ "name":"HS MX / LSH MX","link":"https://penmodding.pm/archives/1665","pic":"../img/lshmx.png","text":"Nom : Hs mx – Créateur :  Mr.MSC – Taille : 18-20 cm – Poids : selon Upsb entre l’impact mx et le mx. nous voila bien avancés. – Insert  : Oui – Lien :  HS Mx / LSH Mx – Moddage : Difficile", "type":"sc"},' +
    '{ "name":"S.S.S Mod (Single Sided Sky Mod)","link":"https://penmodding.pm/archives/1654","pic":"../img/sss.jpg","text":"Name : S.S.S Mod (Single Sided Sky Mod) – Creator : Nachoaddict – Lenght : 20 cm – Weigth : Middle – Insert / Outsert : No – Link : S.S.S Mod (Single Sided Sky Mod) (UPSB) – Modding : Middle", "type":"sc"},' +
    '{ "name":"Mesi G3 Mod","link":"https://penmodding.pm/archives/1492","pic":"../img/mesig3.jpg","text":"Name : Mesi G3 Mod – Creator : Mesi – Lenght : ~ 19.5cm – Weigth : 14g – Insert : Yes – Link : Mesi G3 Mod (YouTube) – Modding : Difficult", "type":"sc"},' +
    '{ "name":"Dragonfly mod","link":"https://penmodding.pm/archives/1471","pic":"../img/dragonfly.jpg","text":"no description available", "type":"sc"},' +


    '{ "name":"RSVP HJSB","link":"https://penmodding.pm/archives/1394","pic":"../img/rsvp hjsb.jpg","text":"Name : RSVP HJSB – Creator : purplet – Lentgh : 21 cm – Weight: 18.5 g – Insert : Yes – Link : RSVP HJSB (GPC) – Modding : Medium/Hard", "type":"sc"},' +
    '{ "name":"Guitrum Retractable MX","link":"https://penmodding.pm/archives/1379","pic":"../img/guitrum.jpg","text":"Name : Guitrum’s Retractable Mx – Creator : +Guitrum+ – Lenght : 18.5 cm – Weigth : As an Mx – Insert : Yes – Link : Guitrum’s Retractable Mx (UPSB) – Modding : Difficult", "type":"sc"},' +
    '{ "name":"Teotoko RSVP MOD","link":"https://penmodding.pm/archives/1375","pic":"../img/teotoko.jpg","text":"Name : teotoko’s RSVP Mod – Creator : Teotoko – Lenght : 19 cm – Weigth : Medium – Insert : Yes – Link : teotoko’s RSVP Mod (UPSB) – Modding : Easy", "type":"sc"},' +
    '{ "name":"Joey Mod","link":"https://penmodding.pm/archives/1320","pic":"../img/joey.jpg","text":"Name : Joey Mod [Signo NX MMTX] – Creator : Joey – Lenght : 20 cm – Weigth : 15g – Insert : Yes – Link : Joey Mod (UPSB) – Modding : Difficult", "type":"sc"},' +
    
    '{ "name":"Nikoo G3 Mod","link":"https://penmodding.pm/archives/1216","pic":"../img/nikoo.png","text":"Name : NIKoo’s G3 mod – Craator : NIKoo – Length : 19 cm – Weight : Heavy – Insert : Yes – Link : NIKoo’s G3 Mod ( UPSB ) – Making : Very easy", "type":"sc"},' +
    
    '{ "name":"Eban Memory DC","link":"https://penmodding.pm/archives/5895","pic":"../img/eban.jpg","text":"Featured picture : credit goes to Eban. – Name : Eban Memory DC – Creator : Unknown, this mod was gifted to Eban by another spinner – Length : 21 cm – Weight : 12 g – Insert : No – Weblink : / – Difficulty : Easy"}]}';